allowBuilds:
  '@swc/core': true
  esbuild: false
minimumReleaseAgeExclude:
  - '@ayu-sh-kr/dota-ast-utils@0.0.4 || 0.0.6'
  - '@ayu-sh-kr/dota-md@0.0.10 || 0.0.12'
  - '@ayu-sh-kr/dota-ui@0.0.21 || 0.0.23'
  - '@ayu-sh-kr/dota-web-type-json@0.0.9 || 0.0.11'
  - '@ayu-sh-kr/dota-wrap@0.0.24 || 0.0.26 || 0.0.27'
  - '@ayu-sh-kr/dota-router@0.0.30 || 0.0.31'
  - '@ayu-sh-kr/dota-core@1.9.8'
  - '@ayu-sh-kr/dota-rendering@0.1.1'
  - '@ayu-sh-kr/dota-ssr@0.0.2'
