allowBuilds:
  '@swc/core': true
  esbuild: false
minimumReleaseAgeExclude:
  - '@ayu-sh-kr/dota-ast-utils@0.0.4'
  - '@ayu-sh-kr/dota-md@0.0.10'
  - '@ayu-sh-kr/dota-ui@0.0.21'
  - '@ayu-sh-kr/dota-web-type-json@0.0.9'
  - '@ayu-sh-kr/dota-wrap@0.0.24'
