import { defineConfig, type Plugin } from "vite";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import {fileURLToPath} from "node:url";
import tailwindcss from "@tailwindcss/vite";
import {dotaVitePlugins} from "@ayu-sh-kr/dota-wrap/vite";

const projectRoot = fileURLToPath(new URL(".", import.meta.url));
const blogRoutes = [
  "/blog/ssr-vs-ssg-rendering-hydration-dom",
  "/blog/aws-app-config-spring-boot-integration",
  "/blog/postgresql-access-control",
  "/blog/distributed-locks-redis",
  "/blog/rate-limiting-token-bucket-spring-boot",
  "/blog/distributed-monolith-extra-invoices",
  "/blog/lambda-pricing-infra-alone",
  "/blog/eventbridge-scheduler-quirks",
  "/blog/business-logic-auth-middleware",
];
const showcaseRoutes = [
  "/showcase/dota-workspace",
  "/showcase/restaurant-oms",
  "/showcase/sacrena",
  "/showcase/indiknots",
  "/showcase/jalans",
  "/showcase/dota-wrap",
  "/showcase/event-pipeline",
  "/showcase/dota-rest",
];

/**
 * Makes Vite preview serve SSG routes through the same canonical URL shape as production.
 *
 * Dota SSG writes a route such as `/blog/article` to `dist/blog/article/index.html`.
 * Vercel redirects the extensionless URL to `/blog/article/`, which lets the host serve
 * that generated document and lets `dotaHydration()` adopt its marked route host. Vite
 * preview otherwise misses the directory document, serves `dist/index.html`, and forces
 * the client router to replace the home route before it can render the requested page.
 *
 * This plugin runs before preview's SPA fallback. It redirects only GET and HEAD requests
 * whose resolved output directory contains an `index.html`; unknown paths still reach the
 * fallback so client-only routes retain their normal behavior. Queries are preserved and
 * requests already using the trailing-slash canonical form pass through unchanged.
 */
const previewSsgRedirects: Plugin = {
  name: "preview-ssg-redirects",

  /**
   * Registers the pre-fallback redirect middleware for `vite preview` only.
   *
   * The output check makes the redirect data-driven: every route generated by the current
   * build is handled without maintaining a second route list in this config. The containment
   * check keeps a malformed URL from resolving a file outside the configured build output.
   */
  configurePreviewServer(server) {
    server.middlewares.use((request, response, next) => {
      if ((request.method !== "GET" && request.method !== "HEAD") || !request.url) {
        next();
        return;
      }

      const url = new URL(request.url, "http://localhost");
      if (url.pathname === "/" || url.pathname.endsWith("/")) {
        next();
        return;
      }

      const outputDirectory = resolve(server.config.build.outDir);
      const staticRouteDirectory = resolve(outputDirectory, `.${url.pathname}`);
      if (!staticRouteDirectory.startsWith(`${outputDirectory}/`) || !existsSync(resolve(staticRouteDirectory, "index.html"))) {
        next();
        return;
      }

      response.writeHead(308, { Location: `${url.pathname}/${url.search}` });
      response.end();
    });
  },
};

export default defineConfig({
  plugins: [
    tailwindcss(),
    previewSsgRedirects,
    ...dotaVitePlugins({
      root: projectRoot,
      logType: "info",
      scanRoots: [
        projectRoot,
        resolve(projectRoot, "node_modules/@ayu-sh-kr/dota-md"),
        resolve(projectRoot, "node_modules/@ayu-sh-kr/dota-ui"),
      ],
      webTypes: {
        outFile: "web-types.json",
        customElementsManifest: { enabled: true },
      },
      eventMap: {
        outFile: "src/event-map.d.ts",
      },
      ssg: {
        entry: "/src/main.ts",
        autoDetectRoutes: true,
        routes: ["/offline", ...blogRoutes, ...showcaseRoutes],
        vercel: true,
      },
    }),
  ],
  resolve: {
    alias: {
      "@app": resolve("./src"),
    },
  },
  publicDir: "public",
});
